# -*- coding: utf-8 -*-
"""agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IvnO552YU9jPMqjVmHIXEym2ikz3oNO2
"""

import matplotlib.pyplot as plt
import os, math, random, time, csv
from collections import namedtuple
import numpy as np
import pandas as pd
import torch, torch.nn as nn, torch.optim as optim
import gym
from gym import spaces
import itertools
import os
import pickle

from ppo import *

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ---------------- PPO agent ----------------
# Ajout de 'hidden' dans la namedtuple
Transition = namedtuple("Transition", ["obs", "apr", "action", "logp", "reward", "value", "done", "adv", "ret", "mean", "std", "hidden"])

class PPOAgent:
    def __init__(self, single_dim, seq_len, action_dim=1, lr=1e-4, clip=0.2, gamma=0.99, lam=0.95):
        self.model = ActorCriticSeq(single_dim, seq_len, action_dim).to(DEVICE)
        self.optimizer = optim.Adam(self.model.parameters(), lr=lr)
        self.clip = clip; self.gamma = gamma; self.lam = lam

    def select_action(self, seq_obs, apr_seq=None, hidden=None):
        # seq_obs: (seq_len, single_dim)
        # On ajoute la dimension batch=1
        obs_t = torch.tensor(seq_obs, dtype=torch.float32, device=DEVICE).unsqueeze(0)
        apr_t = torch.tensor(apr_seq, dtype=torch.float32, device=DEVICE).unsqueeze(0)

        # On passe le hidden state actuel
        with torch.no_grad():
            mean_t, std_t, value_t, next_hidden = self.model(obs_t, apr_t, hidden=hidden)

        mean = mean_t.squeeze(0)
        if std_t.dim() == 0: std = std_t.unsqueeze(0)
        else: std = std_t

        dist = torch.distributions.Normal(mean, std)
        action = dist.sample()
        logp = dist.log_prob(action).sum().item()

        action_np = action.detach().cpu().numpy()
        mean_np = mean.detach().cpu().numpy()
        std_np = std.detach().cpu().numpy()
        value = float(value_t.squeeze(0).detach().cpu().numpy())

        # On retourne next_hidden pour la boucle d'entrainement
        return action_np, float(logp), value, float(np.asarray(mean_np).reshape(-1)[0]), float(np.asarray(std_np).reshape(-1)[0]), next_hidden

    def compute_gae(self, traj, last_value=0.0):
        # (Inchangé)
        rewards = [t.reward for t in traj]; values = [t.value for t in traj]; dones = [t.done for t in traj]
        gae = 0.0; advs = []
        for i in reversed(range(len(rewards))):
            mask = 1.0 - float(dones[i])
            next_value = last_value if i==len(rewards)-1 else values[i+1]
            delta = rewards[i] + self.gamma * next_value * mask - values[i]
            gae = delta + self.gamma * self.lam * mask * gae
            advs.insert(0, gae)
        returns = [a + v for a, v in zip(advs, values)]
        return advs, returns

    def ppo_update(self, buffer, epochs=3, batch_size=64):
        if len(buffer) == 0: return

        # Conversion des données en tenseurs
        obs = torch.tensor(np.stack([b.obs for b in buffer]), dtype=torch.float32, device=DEVICE)
        actions = torch.tensor(np.stack([b.action for b in buffer]), dtype=torch.float32, device=DEVICE)
        old_logps = torch.tensor([b.logp for b in buffer], dtype=torch.float32, device=DEVICE)
        returns = torch.tensor([b.ret for b in buffer], dtype=torch.float32, device=DEVICE)
        advs = torch.tensor([b.adv for b in buffer], dtype=torch.float32, device=DEVICE)
        apr = torch.tensor([b.apr for b in buffer], dtype=torch.float32, device=DEVICE)

        # Gestion des Hidden States pour le Batch Update
        # hidden est un tuple (h, c). Chaque h/c est (1, 1, hidden_dim) car collecté un par un.
        # On doit les concaténer pour former un batch: (1, N, hidden_dim)

        # Extraction de tous les h et c de la liste buffer
        list_h = [b.hidden[0] for b in buffer] # liste de tenseurs (1, 1, H)
        list_c = [b.hidden[1] for b in buffer] # liste de tenseurs (1, 1, H)

        # Concatenation sur la dimension 1 (batch)
        all_h = torch.cat(list_h, dim=1) # (1, N, H)
        all_c = torch.cat(list_c, dim=1) # (1, N, H)

        # Normalisation des avantages
        adv_mean = advs.mean()
        adv_std = advs.std(unbiased=False)
        if not torch.isfinite(adv_std) or adv_std < 1e-6:
            advs = advs - adv_mean
        else:
            advs = (advs - adv_mean) / (adv_std + 1e-8)

        N = obs.shape[0]; idxs = np.arange(N)

        for _ in range(epochs):
            # np.random.shuffle(idxs) # Attention: avec LSTM, mélanger casse un peu la logique temporelle,
            # mais comme on passe les hidden states enregistrés ("Burn-in" state), c'est acceptable pour PPO simple.

            for start in range(0, N, batch_size):
                mb = idxs[start:start+batch_size]

                batch_obs = obs[mb]
                batch_actions = actions[mb]
                batch_old_logps = old_logps[mb]
                batch_returns = returns[mb]
                batch_advs = advs[mb]
                batch_apr = apr[mb]

                # Découpage des hidden states correspondants à ce mini-batch
                # shape attendue par LSTM: (num_layers, batch_size, hidden_dim)
                mb_h = all_h[:, mb, :]
                mb_c = all_c[:, mb, :]
                batch_hidden = (mb_h, mb_c)

                # Forward pass avec l'état caché enregistré
                # Note: on récupère _, _, _ car on ne réutilise pas le output hidden ici pour l'update
                mean, std, vals, _ = self.model(batch_obs, batch_apr, hidden=batch_hidden)

                # Sécurité numérique
                mean = torch.clamp(mean, min=-1e6, max=1e6)
                std = torch.clamp(std, min=1e-6, max=1e6)

                dist = torch.distributions.Normal(mean, std)
                new_logps = dist.log_prob(batch_actions).sum(dim=-1)
                ratio = torch.exp(new_logps - batch_old_logps)

                surr1 = ratio * batch_advs
                surr2 = torch.clamp(ratio, 1.0 - self.clip, 1.0 + self.clip) * batch_advs

                actor_loss = -torch.mean(torch.min(surr1, surr2))
                critic_loss = torch.mean((batch_returns - vals.squeeze(-1))**2)

                loss = actor_loss + 0.5 * critic_loss

                self.optimizer.zero_grad()
                loss.backward()
                nn.utils.clip_grad_norm_(self.model.parameters(), 0.5)
                self.optimizer.step()