# -*- coding: utf-8 -*-
"""AlmgrenChriss1D

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ADEwFz14p03_eR2kGmxlOHDOjVYRapRX
"""

import matplotlib.pyplot as plt
import os, math, random, time, csv
from collections import namedtuple
import numpy as np
import pandas as pd
import torch, torch.nn as nn, torch.optim as optim
import gym
from gym import spaces
import itertools
import os
import pickle

"""# Model Parameters"""

def estimate_ac_parameters(orderbook, levels=10):

    ask = orderbook.iloc[:,0] / 10000.0
    bid = orderbook.iloc[:,2] / 10000.0

    mid = 0.5 * (ask + bid)

    returns = np.diff(mid)

    sigma = np.std(returns)

    spread = np.mean(ask - bid)

    tau = 1

    total_volume = 0

    for l in range(levels):

        ask_vol = orderbook.iloc[:,4*l + 1]
        bid_vol = orderbook.iloc[:,4*l + 3]

        total_volume += ask_vol + bid_vol

    volume = np.mean(total_volume)

    eta = spread / (0.01 * volume)

    gamma = spread / (0.1 * volume)



    return sigma, eta, gamma, tau

"""# Model Almgren-Chriss 1D"""

class AlmgrenChriss1D:
    def __init__(self, lambd, sigma, eta, gamma, tau):
        # Initialize Parameters
        self._lambda = lambd
        self._sigma = sigma
        #self._epsilon = epsilon
        self._eta = eta
        self._gamma = gamma
        self._tau = tau

        self._eta_tilda = self._eta - 0.5*self._gamma*self._tau

        # Ensure Quadratic (for optimization)
        #assert self._eta_tilda > 0

        self._kappa_tilda_squared = (self._lambda*self._sigma**2)/self._eta_tilda
        #print(f'kappa_tilda_squared = {self._kappa_tilda_squared}')

        self._kappa = np.arccosh(0.5*self._kappa_tilda_squared*self._tau**2 + 1)/self._tau
        #print(f'kappa = {self._kappa}')

    def trajectory(self, X, T):
        # Optimal Liquidation Trajectory
        ans = []
        for t in range(T):
            #x = int(np.sinh(self._kappa*(T - t))/np.sinh(self._kappa*T)*X)
            if self._kappa == 0:
              x = X* (1 - t/T)
            else:
              x = np.sinh(self._kappa*(T - t))/np.sinh(self._kappa*T)*X
            #print(f'x = {x}')
            ans.append(x)
        ans.append(0)
        return np.array(ans)

    def strategy(self, X, T):
        # Optimal Liquidation Trade List
        return np.diff(self.trajectory(X,T))

def run_ac_episode(env, volumes):

    obs = env.reset()

    done = False

    rewards = 0

    actions = []

    inventory_path = [env.remaining_inventory]

    t = 0

    while not done:

        remaining = env.remaining_inventory

        #if remaining <= 0:
        #    break

        v = volumes[t]

        action = min(1.0, v / remaining)

        obs, reward, done, info = env.step([action])

        rewards += reward

        actions.append(info["executed"])

        inventory_path.append(env.remaining_inventory)

        t += 1

    return rewards, actions, inventory_path

def train_almgren_chriss(env, n_episodes=200, time_horizon=100, lam = 1e-2):

    episode_rewards = []
    episode_actions = []
    episode_inventory = []

    prev_data = None

    for ep in range(n_episodes):

        if prev_data is None:
            #print('épisode 0: paramètres aléatoires')
            sigma = np.random.uniform(0.0001,0.001)
            eta = np.random.uniform(0.01,0.1)
            gamma = np.random.uniform(0.01,0.1)
            tau = 1

        else:
            #print('paramètres estimés avec les données de l épisode précédente')

            sigma, eta, gamma, tau = estimate_ac_parameters(prev_data)
            #print(f'sigma = {sigma}, eta = {eta}, gamma = {gamma}, tau = {tau}')

        X0 = env.initial_inventory


        model = AlmgrenChriss1D(lam, sigma, eta, gamma, tau)
        trajectory = model.trajectory(X0,time_horizon)
        print(trajectory)
        strategy = -model.strategy(X0,time_horizon)
        print(strategy)

        reward, actions, inventory = run_ac_episode(env, strategy)

        episode_rewards.append(reward)
        episode_actions.append(actions)
        episode_inventory.append(inventory)

        prev_data = env.ob_df.iloc[
            env.idx-time_horizon : env.idx
        ]
        #print(f'envi.idx = {env.idx}')

    return episode_rewards, episode_actions, episode_inventory

"""# Almgren-Chriss aversion au risque nulle: TWAP"""

def TWAP_Strategie(
    env,
    n_episodes=100,
    time_horizon=100
):

    twap1_rewards = []
    twap_episode_action = []      # Recupérer toutes les actions prises à chaque épisode
    global_inventory = []      # Recupérer l'évolution de l'inventaire à chaque épisode

    start_idx = 0

    for ep in range(n_episodes):

        if start_idx >= env.N - 1:
            print("Fin des données.")
            break

        env.reset()

        episode_inventory = []
        episode_inventory.append(env.initial_inventory)
        twap_action = []   # Recupérer toutes les actions de l'épisode actuelle

        done = False

        ep_twap1_reward = 0.0

        initial_inventory = env.initial_inventory

        while not done:

            # ================= TWAP (ENV ISOLÉS) =================

            # --- TWAP statique ---
            twap1_action = env.initial_inventory / (float(env.max_steps) * env.remaining_inventory)

            obs, twap1_r, done, info = env.step([twap1_action])
            ep_twap1_reward += twap1_r


            twap_action.append(info["executed"])
            episode_inventory.append(env.remaining_inventory)

            if done:
                break

        twap1_rewards.append(ep_twap1_reward)
        twap_episode_action.append(twap_action)
        global_inventory.append(episode_inventory)

        start_idx = env.idx

        print(
            f"[TEST Episode {ep:03d}] "
            f"TWAP1={ep_twap1_reward:.6f} | "
        )

    return twap1_rewards, twap_episode_action, global_inventory