# -*- coding: utf-8 -*-
"""environment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UAa4Zb8yjndmY5msjYHb8xsbvLP7b71Y
"""

import matplotlib.pyplot as plt
import os, math, random, time, csv
from collections import namedtuple
import numpy as np
import pandas as pd
import torch, torch.nn as nn, torch.optim as optim
import gym
from gym import spaces
import itertools
import os
import pickle

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

"""# Features"""

# ---------------- Helper: features ----------------
def build_row_features(ob_row, msg_row, levels=5):
    """
    Construit un vecteur d'état normalisé et stationnaire.
    Modifications:
    1. Les volumes sont passés au Log pour gérer les outliers.
    2. Les prix sont exprimés en distance relative au Mid-Price.
    """
    ob = np.array(ob_row, dtype=np.float64)
    vals = ob[:4*levels]

    # Séparation Prix et Volumes
    # Indices pairs (0, 2, ...) sont des PRIX (déjà divisés par 10000 dans la logique LOBSTER brute si nécessaire,
    # mais ici on assume qu'ils sont bruts dans le CSV, donc on divise).
    prices = vals[::2] / 10000.0
    volumes = vals[1::2]

    # --- 1. Calcul du Mid-Price (Référence) ---
    # Le meilleur Ask est à l'index 0, le meilleur Bid est à l'index 2 (dans vals d'origine) -> donc index 0 et 1 de 'prices'
    best_ask = prices[0]
    best_bid = prices[1]

    # Sécurité si carnet vide ou croisé (rare sur données propres mais possible)
    if best_ask == 0 or best_bid == 0:
        mid = 0.0
    else:
        mid = 0.5 * (best_ask + best_bid)

    # --- 2. Normalisation ---
    final_features = []

    sum_ask_vol = 0.0
    sum_bid_vol = 0.0

    for lvl in range(levels):
        # Récupération
        p_ask = prices[2*lvl]      # Ask Price
        v_ask = volumes[2*lvl]     # Ask Size
        p_bid = prices[2*lvl + 1]  # Bid Price
        v_bid = volumes[2*lvl + 1] # Bid Size

        # A) Prix Relatifs (Distance au Mid)
        # On multiplie par un facteur (ex: 100) pour éviter d'avoir des chiffres trop petits (0.0001)
        # Ask est > Mid, Bid est < Mid.
        if mid > 1e-8:
            rel_ask = (p_ask - mid)
            rel_bid = (mid - p_bid) # On inverse pour avoir une distance positive, ou (p_bid - mid) pour négatif.
                                    # Garder le signe est mieux : (p - mid).
            rel_p_ask = p_ask - mid
            rel_p_bid = p_bid - mid
        else:
            rel_p_ask = 0.0
            rel_p_bid = 0.0

        # B) Log-Volumes
        # log(x + 1) pour gérer les 0 et compresser l'échelle
        norm_v_ask = np.log(v_ask + 1.0)
        norm_v_bid = np.log(v_bid + 1.0)

        final_features.extend([rel_p_ask, norm_v_ask, rel_p_bid, norm_v_bid])

        sum_ask_vol += v_ask
        sum_bid_vol += v_bid

    # --- 3. Features Microstructure ---
    spread = best_ask - best_bid
    # Order Book Imbalance (reste sur les volumes bruts pour le calcul, ou log, peu importe, c'est un ratio)
    imbalance = (sum_bid_vol - sum_ask_vol) / (sum_bid_vol + sum_ask_vol + 1e-8)

    last_trade_sign = 0.0
    if msg_row is not None and int(msg_row[1]) == 4:
        try:
            last_trade_sign = float(msg_row[5])
        except Exception:
            last_trade_sign = 0.0

    extras = [spread, imbalance, last_trade_sign] # On retire 'mid' des features car il est absolu et non-stationnaire !

    # Retourne le vecteur concaténé
    return np.array(final_features + extras, dtype=np.float32)

"""# Fonction de liquidation forcée"""

def worst_bid_price(ob_row, remaining_inventory, levels):
    """
    Prix du dernier niveau bid nécessaire pour liquider remaining_inventory.
    """
    cum_vol = 0.0
    last_price = None

    for lvl in range(levels):
        price = ob_row[2 + 4*lvl] / 10000.0   # bid price
        size  = ob_row[3 + 4*lvl]            # bid size
        cum_vol += size
        last_price = price
        if cum_vol >= remaining_inventory:
            return price

    # Pas assez de liquidité visible → pire bid observable
    return last_price

"""# Environnement avec continuité inter-épisode"""

# Utilisation du Carnet avec plus de 10 niveaux de profondeur et affichage de toutes les profondeurs

class LOBSTEREnvSeq(gym.Env):

    def __init__(
        self,
        orderbook,
        message,
        seq_len=8,
        initial_inventory=200,
        max_steps=None,
        visible_levels=5,
        total_levels=10
    ):
        super().__init__()

        self.ob_df = orderbook
        self.msg_df = message
        assert len(self.ob_df) == len(self.msg_df)

        self.visible_levels = visible_levels
        self.total_levels = total_levels
        self.seq_len = seq_len
        self.initial_inventory = float(initial_inventory)

        self.N = len(self.ob_df)
        self.max_steps = max_steps or self.N

        self.single_dim = 4 * self.visible_levels + 3 + 2

        self.initialized = False

        self.observation_space = spaces.Box(
            low=-np.inf,
            high=np.inf,
            shape=(self.seq_len, self.single_dim),
            dtype=np.float32
        )

        self.action_space = spaces.Box(
            low=0.0,
            high=1.0,
            shape=(1,),
            dtype=np.float32
        )

        # [DEEP] carnet profond
        self.deep_bids = []
        self.deep_asks = []

        self.reset()

    # ======================================================
    # ================= OUTILS CARNET ======================
    # ======================================================



    def _print_lob_deep(self, title, max_depth=20):
        """
        Affiche le carnet profond au-delà de L10.
        max_depth = nombre total de niveaux affichés (>= total_levels)
        """
        print(f"\n--- {title} (DEEP BOOK L1–L{max_depth}) ---")

        max_bid = min(len(self.deep_bids), max_depth)
        max_ask = min(len(self.deep_asks), max_depth)

        depth = max(max_bid, max_ask)

        for i in range(depth):
            # ASK
            if i < len(self.deep_asks):
                ask_p, ask_q = self.deep_asks[i]
                ask_str = f"ASK {ask_q:6.0f} @ {ask_p:8.4f}"
            else:
                ask_str = "ASK      -"

            # BID
            if i < len(self.deep_bids):
                bid_p, bid_q = self.deep_bids[i]
                bid_str = f"BID {bid_q:6.0f} @ {bid_p:8.4f}"
            else:
                bid_str = "BID      -"

            flag = ""
            if i >= self.total_levels:
                flag = "  <-- > L10"

            print(f"L{i+1:02d} | {ask_str} || {bid_str}{flag}")



    def _init_deep_book_from_row(self, row):
        """Initialise le carnet profond à partir d'une ligne LOBSTER"""
        self.deep_bids = []
        self.deep_asks = []

        for lvl in range(self.total_levels):
            ask_p = row[4*lvl] / 10000.0
            ask_q = row[4*lvl + 1]
            bid_p = row[4*lvl + 2] / 10000.0
            bid_q = row[4*lvl + 3]

            if ask_q > 0:
                self.deep_asks.append([ask_p, ask_q])
            if bid_q > 0:
                self.deep_bids.append([bid_p, bid_q])

        self._sort_deep_book()
        self._project_deep_to_lob()

    def _sort_deep_book(self):
        self.deep_bids.sort(key=lambda x: -x[0])
        self.deep_asks.sort(key=lambda x: x[0])

    def _project_deep_to_lob(self):
        """Projette le carnet profond vers L1–L10 (current_ob)"""
        ob = np.zeros(4 * self.total_levels, dtype=np.float64)

        for i in range(self.total_levels):
            if i < len(self.deep_asks):
                ob[4*i]   = self.deep_asks[i][0] * 10000.0
                ob[4*i+1] = self.deep_asks[i][1]
            else:
                ob[4*i]   = 9999999999
                ob[4*i+1] = 0

            if i < len(self.deep_bids):
                ob[4*i+2] = self.deep_bids[i][0] * 10000.0
                ob[4*i+3] = self.deep_bids[i][1]
            else:
                ob[4*i+2] = -9999999999
                ob[4*i+3] = 0

        self.current_ob[:4*self.total_levels] = ob

    def _print_lob_visible(self, title):
        print(f"\n--- {title} (VISIBLE LEVELS L1–L{self.visible_levels}) ---")
        for i in range(self.visible_levels):
            ask_p = self.current_ob[4*i] / 10000.0
            ask_q = self.current_ob[4*i+1]
            bid_p = self.current_ob[4*i+2] / 10000.0
            bid_q = self.current_ob[4*i+3]

            print(
                f"L{i+1} | "
                f"ASK {ask_q:6.0f} @ {ask_p:8.4f} || "
                f"BID {bid_q:6.0f} @ {bid_p:8.4f}"
            )

    def _print_lob_internal(self, title):
        print(f"\n--- {title} (INTERNAL LEVELS L{self.visible_levels+1}–L{self.total_levels}) ---")
        for i in range(self.visible_levels, self.total_levels):
            ask_p = self.current_ob[4*i] / 10000.0
            ask_q = self.current_ob[4*i+1]
            bid_p = self.current_ob[4*i+2] / 10000.0
            bid_q = self.current_ob[4*i+3]

            print(
                f"L{i+1} | "
                f"ASK {ask_q:6.0f} @ {ask_p:8.4f} || "
                f"BID {bid_q:6.0f} @ {bid_p:8.4f}"
            )

    # ======================================================
    # ================= MESSAGE EVENT ======================
    # ======================================================

    def _apply_message(self, msg_row):
        msg_type = int(msg_row[1])
        size = float(msg_row[3])
        price = float(msg_row[4]) / 10000.0
        direction = int(msg_row[5])

        book = self.deep_bids if direction == 1 else self.deep_asks

        if msg_type == 1:  # new limit
            for lvl in book:
                if abs(lvl[0] - price) < 1e-6:
                    lvl[1] += size
                    break
            else:
                book.append([price, size])

        elif msg_type in (2, 3, 4):  # cancel / delete / exec
            for lvl in book:
                if abs(lvl[0] - price) < 1e-6:
                    lvl[1] = max(0.0, lvl[1] - size)
                    break

        self.deep_bids = [b for b in self.deep_bids if b[1] > 0]
        self.deep_asks = [a for a in self.deep_asks if a[1] > 0]

        self._sort_deep_book()
        self._project_deep_to_lob()

    # ======================================================
    # ================= ACTION AGENT =======================
    # ======================================================

    def _apply_market_sell(self, qty):
        executed = 0.0
        cost = 0.0

        for lvl in self.deep_bids:
            if executed >= qty:
                break
            take = min(lvl[1], qty - executed)
            lvl[1] -= take
            executed += take
            cost += take * lvl[0]
            #print(f'take = {take} at price = {lvl[0]}')

        self.deep_bids = [b for b in self.deep_bids if b[1] > 0]
        self._sort_deep_book()
        self._project_deep_to_lob()

        avg_price = cost / executed if executed > 0 else 0.0
        return executed, avg_price

    # ======================================================
    # ========================= RESET ======================
    # ======================================================

    def reset(self, hard_reset=False):

        if hard_reset or not self.initialized:
            self.idx = 0
            self.current_ob = (
                self.ob_df.iloc[self.idx].values
                .astype(np.float64)
                .copy()
            )
            self._init_deep_book_from_row(self.current_ob)
            self.initialized = True

        self.step_count = 0
        self.remaining_inventory = self.initial_inventory

        best_ask = self.current_ob[0] / 10000.0
        best_bid = self.current_ob[2] / 10000.0
        self.arrival_price = 0.5 * (best_ask + best_bid)

        base_feat = build_row_features(
            self.current_ob[:4*self.visible_levels],
            self.msg_df.iloc[self.idx].values,
            self.visible_levels
        )

        f0 = np.concatenate(
            [base_feat, np.array([1.0, 1.0], dtype=np.float32)]
        )

        self.buffer = (
            [np.zeros(self.single_dim, dtype=np.float32)
             for _ in range(self.seq_len - 1)]
            + [f0]
        )

        return np.stack(self.buffer)

    # ======================================================
    # ========================= STEP =======================
    # ======================================================

    def step(self, action):
        #print(f"\n================ STEP {self.step_count} =================")

        msg_row = self.msg_df.iloc[self.idx].values
        self._apply_message(msg_row)
        #self._print_lob_visible("LOB APRÈS MESSAGE")
        #self._print_lob_internal("LOB INTERNE APRÈS MESSAGE")

        a = float(np.clip(action[0], 0.0, 1.0))
        qty = a * self.remaining_inventory

        executed, avg_price = self._apply_market_sell(qty)
        #print(f"Action agent = vente {qty:.2f}")
        #self._print_lob_visible("LOB APRÈS ACTION AGENT")
        #self._print_lob_internal("LOB INTERNE APRÈS ACTION")
        #self._print_lob_deep("LOB PROFOND APRÈS MESSAGE", max_depth=20)
        #self._print_lob_deep("LOB PROFOND APRÈS ACTION AGENT", max_depth=20)


        reward = 0.0
        # --- Reward instantanée ---
        if executed > 0:
            pnl = (avg_price - self.arrival_price) * executed
            reward = (pnl / (self.arrival_price * self.initial_inventory)) * 100.0
            #print(f'reward = {reward}')

        self.remaining_inventory -= executed

        # --- pénalité d'inventaire (à chaque step) ---
        inventory_penalty = -0.01 * (self.remaining_inventory / self.initial_inventory)**2
        reward += inventory_penalty

        self.idx += 1
        self.step_count += 1

        done = (
            self.step_count >= self.max_steps
            or self.idx >= self.N - 1
        )
        # ---------------- LIQUIDATION FORCÉE -----------------------------------------------------
        if done and self.remaining_inventory > 0:
          liq_price = worst_bid_price(self.current_ob, self.remaining_inventory, self.total_levels)
          #print(f'Inventaire restant = {self.remaining_inventory}')

          liq_pnl = (liq_price - self.arrival_price) * self.remaining_inventory

          liq_penalty = (liq_pnl / (self.arrival_price * self.initial_inventory)) * 100.0

          reward += liq_penalty
          # ----------------------------------------------------------------------------------------

        if not done:
            base_feat = build_row_features(
                self.current_ob[:4*self.visible_levels],
                self.msg_df.iloc[self.idx].values,
                self.visible_levels
            )

            norm_inv = self.remaining_inventory / self.initial_inventory
            norm_time = (self.max_steps - self.step_count) / self.max_steps

            f = np.concatenate(
                [base_feat, np.array([norm_inv, norm_time], dtype=np.float32)]
            )

            self.buffer.pop(0)
            self.buffer.append(f)
            obs = np.stack(self.buffer)
        else:
            obs = np.zeros((self.seq_len, self.single_dim), dtype=np.float32)

        info = {
            "executed": executed,
            "avg_exec_price": avg_price
        }

        return obs, float(reward), done, info