# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fesGXbexq9JFjWXxgDChf5zxGT6_syiF
"""

from environment import *
from ppo import *
from agent import *
from train import *
from AlmgrenChriss1D import *

import pandas as pd

"""# Data"""

DATASET = "AAPL"

LOB = pd.read_csv(f"data/{DATASET}/orderbook.csv", header=None)

MSG = pd.read_csv(f"data/{DATASET}/message.csv", header=None)

# Train set, validation set and Test set
N = len(LOB)

train_end = int(0.70 * N)
val_end   = int(0.85 * N)

LOB_train = LOB.iloc[:train_end]
MSG_train = MSG.iloc[:train_end]

LOB_val = LOB.iloc[train_end:val_end]
MSG_val = MSG.iloc[train_end:val_end]

LOB_test = LOB.iloc[val_end:]
MSG_test = MSG.iloc[val_end:]

"""# Modèle Almgren-Chriss"""

# TWAP on Train Dataset
twap_env_train = LOBSTEREnvSeq(LOB_train, MSG_train, seq_len = 1, initial_inventory=50, max_steps=10)
twap_rewards_train, twap_train_episode_action, twap_train_global_inventory =  TWAP_Strategie(twap_env_train, n_episodes=18882, time_horizon=10)

# Moyenne Twap des actions de train
#twap_train_episode_action.pop() # Suppression du dernier élément de ce vecteur pour éviter les problème de dimension
mean_twap_train_action = np.mean(twap_train_episode_action, axis=0)
mean_incr_train_action_twap = np.cumsum(mean_twap_train_action)

# Moyenne Twap des inventaires de train
#twap_train_global_inventory.pop() # Suppression du dernier élément de ce vecteur pour éviter les problème de dimension
mean_twap_train_global_inventory = np.mean(twap_train_global_inventory, axis=0)

# TWAP on Test Dataset
twap_env_val = LOBSTEREnvSeq(LOB_test, MSG_test, seq_len = 1, initial_inventory=50, max_steps=10)
twap_rewards_eval, twap_val_action, twap_val_global_inventory =  TWAP_Strategie(twap_env_val, n_episodes=4046, time_horizon=10)
# Moyenne des actions de validation
#twap_val_action.pop() # Suppression du dernier élément de ce vecteur pour éviter les problème de dimension
mean_twap_val_action = np.mean(twap_val_action, axis=0)
mean_incr_val_action_twap = np.cumsum(mean_twap_val_action)
# Moyenne des inventaires de validation
#twap_val_global_inventory.pop() # Suppression du dernier élément de ce vecteur pour éviter les problème de dimension
mean_twap_val_global_inventory = np.mean(twap_val_global_inventory, axis=0)

# AC on training set
ac_env_train = LOBSTEREnvSeq(LOB_train, MSG_train, seq_len = 1, initial_inventory=50, max_steps=10)
ac_rewards_train, ac_actions_train, ac_inventory_train = train_almgren_chriss(ac_env_train, n_episodes=18882, time_horizon=10, lam = 9)
# Moyenne des actions AC de train
#ac_actions_train.pop() # Suppression du dernier élément de ce vecteur pour éviter les problème de dimension
ac_mean_actions_train = np.mean(ac_actions_train,axis=0)
cum_ac_mean_actions_train =np.cumsum(ac_mean_actions_train)
# Moyenne des inventaires AC de train
ac_inventory_train.pop() # Suppression du dernier élément de ce vecteur pour éviter les problème de dimension
ac_inventory_mean_train = np.mean(ac_inventory_train,axis=0)

# Ac on Test Dataset
ac_env_val = LOBSTEREnvSeq(LOB_test, MSG_test, seq_len = 1, initial_inventory=50, max_steps=10)
ac_rewards_val, ac_actions_val, ac_inventory_val = train_almgren_chriss(ac_env_val, n_episodes=4046, time_horizon=10, lam = 9)
# Moyenne des actions AC de train
#ac_actions_val.pop() # Suppression du dernier élément de ce vecteur pour éviter les problème de dimension
ac_mean_actions_val = np.mean(ac_actions_val,axis=0)
cum_ac_mean_actions_val =np.cumsum(ac_mean_actions_val)
# Moyenne des inventaires AC de train
#ac_inventory_val.pop() # Suppression du dernier élément de ce vecteur pour éviter les problème de dimension
ac_inventory_mean_val = np.mean(ac_inventory_val,axis=0)

"""# Modèle PPO + LSTM"""

# --- Hyperparamètres Optimaux ---
param_grid = {
    'lr': [3e-05],
    'lam': [0.93],
    'batch_size': [32]
}

# Générer toutes les combinaisons
keys, values = zip(*param_grid.items())
combinations = [dict(zip(keys, v)) for v in itertools.product(*values)]

print(f"Optimisation sur {len(combinations)} combinaisons...")

results_test_aapl = {}

for i, params in enumerate(combinations):
    print(f"\n--- Combinaison {i+1}/{len(combinations)} : {params} ---")

    # 1. Initialisation Environnement avec seq_len spécifique
    # Note: On réinstancie l'env pour changer seq_len correctement
    current_env = LOBSTEREnvSeq(LOB_train, MSG_train, seq_len = 1, initial_inventory=20, max_steps=10)
    current_eval_env = LOBSTEREnvSeq(LOB_test, MSG_test, seq_len = 1, initial_inventory=20, max_steps=10)

    # 2. Initialisation Agent
    current_agent = PPOAgent(single_dim=current_env.single_dim, seq_len = 1, action_dim=1, lr=params['lr'], lam = params['lam'])

    # 3. Entraînement (Sur la partie TRAIN seulement)
    train_agent_rewards, train_agent_action, train_global_inventory = train_moving_window(current_agent, current_env, n_episodes = 28026, time_horizon = 10, batch_size = params['batch_size'])
    # Moyenne des actions de train
    mean_train_action_agent = np.mean(train_agent_action, axis=0)
    mean_incr_train_action_agent = np.cumsum(mean_train_action_agent)
    # Moyenne des inventaires de train
    mean_train_remaining_inventory_agent = np.mean(train_global_inventory, axis=0)

    # 4. Agent on TEST set
    val_agent_rewards, val_agent_action, val_global_inventory = evaluate_agent(current_agent, current_eval_env, n_episodes=6005, time_horizon=10)
    # Moyenne des actions
    mean_agent_val_action = np.mean(val_agent_action, axis=0)
    mean_incr_val_action_agent = np.cumsum(mean_agent_val_action)
    # Moyenne des inventaires
    mean_val_global_inventory_agent = np.mean(val_global_inventory, axis=0)

    results_test_aapl[i+1] = {
        "params": params,

        "train": {
            "agent reward": train_agent_rewards,
            "Twap reward": twap_rewards_train,
            "AC reward": ac_rewards_train,
            "Agent Mean action": mean_train_action_agent,
            "Twap mean action": mean_twap_train_action,
            "AC mean action": ac_mean_actions_train,
            "Agent increase Mean action": mean_incr_train_action_agent,
            "Twap increase mean action": mean_incr_train_action_twap,
            "AC increase mean action": cum_ac_mean_actions_train,
            "Agent remaining inventory": mean_train_remaining_inventory_agent,
            "Twap remaining inventory": mean_twap_train_global_inventory,
            "AC remaining inventory": ac_inventory_mean_train,
        },

        "evaluation": {
            "agent reward": val_agent_rewards,
            "Twap reward": twap_rewards_eval,
            "AC reward": ac_rewards_val,
            "Agent Mean action": mean_agent_val_action,
            "Twap mean action": mean_twap_val_action,
            "AC mean action": ac_mean_actions_val,
            "Agent increase Mean action": mean_incr_val_action_agent,
            "Twap increase mean action": mean_incr_val_action_twap,
            "AC increase mean action": cum_ac_mean_actions_val,
            "Agent remaining inventory": mean_val_global_inventory_agent,
            "Twap remaining inventory": mean_twap_val_global_inventory,
            "AC remaining inventory": ac_inventory_mean_val,
        }
    }

"""# Visualisation sur le test set"""

n_rows = len(results_test_aapl)
n_cols = 4

fig, axes = plt.subplots(n_rows, n_cols, figsize=(24, 5 * n_rows))

# Cas particulier si une seule ligne
if n_rows == 1:
    axes = axes.reshape(1, -1)

for row, (i, res) in enumerate(results_test_aapl.items()):

    agent_rewards = np.array(res["evaluation"]["agent reward"])
    twap_rewards = np.array(res["evaluation"]["Twap reward"])
    AC_rewards = np.array(res["evaluation"]["AC reward"])
    # Moyennes
    agent_mean = agent_rewards.mean()
    twap_mean = twap_rewards.mean()
    AC_mean = AC_rewards.mean()
    # Médianes
    agent_median = np.median(agent_rewards)
    twap_median = np.median(twap_rewards)
    AC_median = np.median(AC_rewards)

    # ───── Colonne 1 : Rewards ─────
    axes[row, 0].plot(res["evaluation"]["Twap reward"], label="Twap reward")
    axes[row, 0].plot(res["evaluation"]["AC reward"], label="AC reward")
    axes[row, 0].plot(res["evaluation"]["agent reward"], label="Agent PPO reward")
    axes[row, 0].set_title(f"PPO – Validation | Rewards | {res['params']}")
    axes[row, 0].set_xlabel("Episode")
    axes[row, 0].set_ylabel("Récompense cumulée")
    axes[row, 0].legend()

    # ───── Colonne 2 : Inventory ─────
    axes[row, 1].plot(res["evaluation"]["Twap remaining inventory"], label="Twap mean remaining inventory")
    axes[row, 1].plot(res["evaluation"]["AC remaining inventory"], label="AC mean remaining inventory")
    axes[row, 1].plot(res["evaluation"]["Agent remaining inventory"], label="Agent mean remaining inventory")
    axes[row, 1].set_title(f"PPO – Validation | Inventory | {res['params']}")
    axes[row, 1].set_xlabel("Time")
    axes[row, 1].set_ylabel("Inventory restant")
    axes[row, 1].legend()

    # ───── Colonne 3 : Actions ─────
    axes[row, 2].plot(res["evaluation"]["Twap increase mean action"], label="Twap increase mean action")
    axes[row, 2].plot(res["evaluation"]["AC increase mean action"], label="AC increase mean action")
    axes[row, 2].plot(res["evaluation"]["Agent increase Mean action"], label="Agent increase mean action")
    axes[row, 2].set_title(f"PPO – Validation | Actions | {res['params']}")
    axes[row, 2].set_xlabel("Time")
    axes[row, 2].set_ylabel("Action cumulée")
    axes[row, 2].legend()

    # ───── Colonne 4 : Distribution des Rewards ─────
    axes[row, 3].hist(res["evaluation"]["Twap reward"], bins=50, alpha=0.6, label="Twap reward")
    axes[row, 3].hist(res["evaluation"]["AC reward"], bins=50, alpha=0.6, label="AC reward")
    axes[row, 3].hist(res["evaluation"]["agent reward"], bins=50, alpha=0.6, label="Agent reward")
    # Lignes verticales - Agent
    axes[row, 3].axvline(agent_mean, color="red", linestyle="--", linewidth=2, label=f"Agent mean = {agent_mean:.2f}")
    axes[row, 3].axvline(agent_median,color="green", linestyle=":", linewidth=2, label=f"Agent median = {agent_median:.2f}")
    # Lignes verticales - TWAP
    #axes[row, 3].axvline(twap_mean, linestyle="--", linewidth=2, label="TWAP mean")
    #axes[row, 3].axvline(twap_median, linestyle=":", linewidth=2, label="TWAP median")
    # Lignes verticales - TWAP
    #axes[row, 3].axvline(AC_mean, linestyle="--", linewidth=2, label="AC mean")
    #axes[row, 3].axvline(AC_median, linestyle=":", linewidth=2, label="AC median")
    axes[row, 3].set_title(f"Reward Distribution | {res['params']}")
    axes[row, 3].set_xlabel("Reward")
    axes[row, 3].set_ylabel("Fréquence")
    axes[row, 3].legend()

plt.tight_layout()
plt.show()

"""Résultats statistiques"""

summary_results_test_aapl = {}

for key, res in results_test_aapl.items():

    # Rewards brutes
    train_agent_rewards = np.array(res["train"]["agent reward"])
    train_twap_rewards  = np.array(res["train"]["Twap reward"])
    train_AC_rewards  = np.array(res["train"]["AC reward"])

    val_agent_rewards   = np.array(res["evaluation"]["agent reward"])
    val_twap_rewards    = np.array(res["evaluation"]["Twap reward"])
    val_AC_rewards    = np.array(res["evaluation"]["AC reward"])

    # 1) Moyenne et variance des rewards agent
    mean_train_agent_reward = np.mean(train_agent_rewards)
    mean_val_agent_reward   = np.mean(val_agent_rewards)
    std_train_agent_reward = np.std(train_agent_rewards)
    std_val_agent_reward   = np.std(val_agent_rewards)

    # 2) Différences point par point (train et val)
    diff_train_rewards_twap = train_agent_rewards - train_twap_rewards
    diff_train_rewards_AC = train_agent_rewards - train_AC_rewards
    diff_val_rewards_twap = val_agent_rewards - val_twap_rewards
    diff_val_rewards_AC = val_agent_rewards - val_AC_rewards

    # 3) Moyennes et Variance des différences point par point
    mean_diff_train_rewards_twap = np.mean(diff_train_rewards_twap)
    mean_diff_train_rewards_AC = np.mean(diff_train_rewards_AC)
    mean_diff_val_rewards_twap = np.mean(diff_val_rewards_twap)
    mean_diff_val_rewards_AC = np.mean(diff_val_rewards_AC)
    std_diff_train_rewards_twap = np.std(diff_train_rewards_twap)
    std_diff_train_rewards_AC = np.std(diff_train_rewards_AC)
    std_diff_val_rewards_twap = np.std(diff_val_rewards_twap)
    std_diff_val_rewards_AC = np.std(diff_val_rewards_AC)

    # 4) Comparaison Agent vs TWAP and AC (à partir des différences)

    # ----- TRAIN -----
    agent_better_train_twap = diff_train_rewards_twap > 0
    agent_better_train_AC = diff_train_rewards_AC > 0
    twap_better_train  = diff_train_rewards_twap < 0
    AC_better_train  = diff_train_rewards_AC < 0

    n_agent_better_train_twap = np.sum(agent_better_train_twap)
    n_agent_better_train_AC = np.sum(agent_better_train_AC)
    n_twap_better_train  = np.sum(twap_better_train)
    n_AC_better_train  = np.sum(AC_better_train)

    mean_agent_better_twap_train = (np.mean(diff_train_rewards_twap[agent_better_train_twap])  if n_agent_better_train_twap > 0 else 0.0)
    mean_agent_better_AC_train = (np.mean(diff_train_rewards_AC[agent_better_train_AC])  if n_agent_better_train_AC > 0 else 0.0)

    mean_twap_better_train = (np.mean(-diff_train_rewards_twap[twap_better_train])  if n_twap_better_train > 0 else 0.0)
    mean_AC_better_train = (np.mean(-diff_train_rewards_AC[AC_better_train])  if n_AC_better_train > 0 else 0.0)

    glr_train_twap = mean_agent_better_twap_train/mean_twap_better_train
    glr_train_AC = mean_agent_better_AC_train/mean_AC_better_train

    # ----- VALIDATION -----
    agent_better_val_twap = diff_val_rewards_twap > 0
    agent_better_val_AC = diff_val_rewards_AC > 0
    twap_better_val  = diff_val_rewards_twap < 0
    AC_better_val  = diff_val_rewards_AC < 0

    n_agent_better_val_twap = np.sum(agent_better_val_twap)
    n_agent_better_val_AC = np.sum(agent_better_val_AC)
    n_twap_better_val  = np.sum(twap_better_val)
    n_AC_better_val  = np.sum(AC_better_val)

    mean_agent_better_val_twap = (np.mean(diff_val_rewards_twap[agent_better_val_twap])  if n_agent_better_val_twap > 0 else 0.0)
    mean_agent_better_val_AC = (np.mean(diff_val_rewards_AC[agent_better_val_AC])  if n_agent_better_val_AC > 0 else 0.0)

    mean_twap_better_val = (np.mean(-diff_val_rewards_twap[twap_better_val])  if n_twap_better_val > 0 else 0.0 )
    mean_AC_better_val = (np.mean(-diff_val_rewards_AC[AC_better_val])  if n_AC_better_val > 0 else 0.0 )

    glr_val_twap = mean_agent_better_val_twap/mean_twap_better_val
    glr_val_AC = mean_agent_better_val_AC/mean_AC_better_val

    summary_results_test_aapl[key] = {
        "params": res["params"],

        "train": {
            "mean train agent reward": mean_train_agent_reward,
            "std train agent reward": std_train_agent_reward,
            "delta train agent twap": diff_train_rewards_twap,
            "delta train agent AC": diff_train_rewards_AC,
            "mean delta train twap": mean_diff_train_rewards_twap,
            "mean delta train AC": mean_diff_train_rewards_AC,
            "std delta train twap": std_diff_train_rewards_twap,
            "std delta train AC": std_diff_train_rewards_AC,
            "agent beats twap count": n_agent_better_train_twap,
            "agent beats AC count": n_agent_better_train_AC,
            "agent beats twap mean delta": mean_agent_better_twap_train,
            "agent beats AC mean delta": mean_agent_better_AC_train,
            "twap beats agent count": n_twap_better_train,
            "AC beats agent count": n_AC_better_train,
            "twap beats agent mean delta": mean_twap_better_train,
            "AC beats agent mean delta": mean_AC_better_train,
            "GLR Twap": glr_train_twap,
            "GLR AC": glr_train_AC,
        },

        "evaluation": {
            "mean val agent reward": mean_val_agent_reward,
            "std val agent reward": std_val_agent_reward,
            "delta val agent twap": diff_val_rewards_twap,
            "delta val agent AC": diff_val_rewards_AC,
            "mean delta val Twap": mean_diff_val_rewards_twap,
            "mean delta val AC": mean_diff_val_rewards_AC,
            "std delta val Twap": std_diff_val_rewards_twap,
            "std delta val AC": std_diff_val_rewards_AC,
            "agent beats twap count": n_agent_better_val_twap,
            "agent beats AC count": n_agent_better_val_AC,
            "agent beats twap mean delta": mean_agent_better_val_twap,
            "agent beats AC mean delta": mean_agent_better_val_AC,
            "twap beats agent count": n_twap_better_val,
            "AC beats agent count": n_AC_better_val,
            "twap beats agent mean delta": mean_twap_better_val,
            "AC beats agent mean delta": mean_AC_better_val,
            "GLR Twap": glr_val_twap,
            "GLR AC": glr_val_AC,
        }
    }

"""Statistiques sur le test set"""

for k, v in summary_results_test_aapl.items():
    print(f"\nParams {k}                   : {v['params']}")
    print(f"mean val agent reward          : {v["evaluation"]['mean val agent reward']:.3f}")
    print(f"std val agent reward           : {v["evaluation"]['std val agent reward']:.3f}")
    print(f"mean delta val Twap            : {v["evaluation"]['mean delta val Twap']:.3f}")
    print(f"mean delta val AC              : {v["evaluation"]['mean delta val AC']:.3f}")
    print(f"std delta val Twap             : {v["evaluation"]['std delta val Twap']:.3f}")
    print(f"std delta val AC               : {v["evaluation"]['std delta val AC']:.3f}")
    print(f"agent beats twap count         : {v["evaluation"]['agent beats twap count']:.3f}")
    print(f"agent beats AC count           : {v["evaluation"]['agent beats AC count']:.3f}")
    print(f"agent beats twap mean delta    : {v["evaluation"]['agent beats twap mean delta']:.3f}")
    print(f"agent beats AC mean delta      : {v["evaluation"]['agent beats AC mean delta']:.3f}")
    print(f"twap beats agent count         : {v["evaluation"]['twap beats agent count']:.3f}")
    print(f"AC beats agent count           : {v["evaluation"]['AC beats agent count']:.3f}")
    print(f"twap beats agent mean delta    : {v["evaluation"]['twap beats agent mean delta']:.3f}")
    print(f"AC beats agent mean delta      : {v["evaluation"]['AC beats agent mean delta']:.3f}")
    print(f"GLR Twap                       : {v["evaluation"]['GLR Twap']:.3f}")
    print(f"GLR AC                         : {v["evaluation"]['GLR AC']:.3f}")