# -*- coding: utf-8 -*-
"""ppo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_rAwQ8aQ7YqPTbcKPjwctzGS0njbpybi
"""

import matplotlib.pyplot as plt
import os, math, random, time, csv
from collections import namedtuple
import numpy as np
import pandas as pd
import torch, torch.nn as nn, torch.optim as optim
import gym
from gym import spaces
import itertools
import os
import pickle

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

"""# PPO + LSTM"""

# ---------------- Model ----------------
class ActorCriticSeq(nn.Module):
    def __init__(self, single_dim, seq_len, action_dim=1, fc_hid=128, lstm_hid=128):
        super().__init__()
        self.encoder = nn.Sequential(
            nn.Linear(single_dim, fc_hid),
            nn.ReLU(),
            nn.Linear(fc_hid, fc_hid),
            nn.ReLU()
        )
        self.post_cat = nn.Linear(fc_hid + 2, lstm_hid)
        self.lstm = nn.LSTM(lstm_hid, lstm_hid, num_layers=1, batch_first=True)
        self.actor_mean = nn.Linear(lstm_hid, action_dim)
        self.critic = nn.Linear(lstm_hid, 1)
        self.actor_log_std = nn.Linear(lstm_hid, action_dim)

    def forward(self, seq_obs, apr_seq=None, hidden=None):
        # seq_obs: (batch, seq_len, single_dim)
        b, s, o = seq_obs.shape
        x = seq_obs.view(b*s, o)

        enc = self.encoder(x)  # (b*s, fc_hid)

        if apr_seq is None:
            apr = torch.zeros((b*s, 2), device=enc.device)
        else:
            apr = apr_seq.view(b*s, 2)

        cat = torch.cat([enc, apr], dim=-1)
        post = torch.relu(self.post_cat(cat)).view(b, s, -1)


        # On récupère next_hidden (hn, cn)
        lstm_out, next_hidden = self.lstm(post, hidden)

        last = lstm_out[:, -1, :]

        mean = self.actor_mean(last)
        log_std = self.actor_log_std(last)
        std = torch.exp(log_std).clamp(1e-6, 10.0)
        value = self.critic(last).squeeze(-1)

        # On retourne aussi next_hidden
        return mean, std, value, next_hidden