# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QQfyTBrM8fUIiRGpD0W06zi_l4prkTwc
"""

import matplotlib.pyplot as plt
import os, math, random, time, csv
from collections import namedtuple
import numpy as np
import pandas as pd
import torch, torch.nn as nn, torch.optim as optim
import gym
from gym import spaces
import itertools
import os
import pickle

from environment import *
from ppo import *
from agent import *
from AlmgrenChriss1D import *

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

"""# Train"""

def train_moving_window(
    agent,
    env,
    n_episodes=200,
    time_horizon=100,
    ppo_epochs=10,
    batch_size=64,
    update_every_n_episodes=10  # <--- NOUVEAU PARAMÈTRE
):
    agent_episode_rewards = []
    agent_episode_action = []      # Recupérer toutes les actions prises à chaque épisode
    global_inventory = []      # Recupérer l'évolution de l'inventaire à chaque épisode
    start_idx = 0

    # Ce buffer accumulera les expériences de plusieurs épisodes
    global_buffer = []

    for ep in range(n_episodes):
        if start_idx >= env.N - 1:
            break

        obs = env.reset(hard_reset=(ep == 0))
        env.max_steps = time_horizon

        episode_inventory = []
        episode_inventory.append(env.initial_inventory)
        agent_action = []   # Recupérer toutes les actions de l'épisode actuelle

        traj = []
        done = False
        prev_action, prev_reward = 0.0, 0.0
        apr_buf = [[0.0, 0.0] for _ in range(env.seq_len)]
        ep_agent_reward = 0.0
        lstm_hidden = None

        # --- Collecte d'un épisode ---
        while not done:
            apr_buf.pop(0)
            apr_buf.append([prev_action, prev_reward])
            apr = np.array(apr_buf, dtype=np.float32)

            action, logp, value, mean, std, next_hidden = agent.select_action(obs, apr, hidden=lstm_hidden)
            action_val = float(np.asarray(action).reshape(-1)[0])

            next_obs, reward, done, info = env.step([action_val])
            ep_agent_reward += reward
            agent_action.append(info["executed"])
            episode_inventory.append(env.remaining_inventory)

            traj.append(
                Transition(
                    obs=obs, apr=apr, action=np.array([action_val], dtype=np.float32),
                    logp=logp, reward=reward, value=value, done=done,
                    adv=0.0, ret=0.0, mean=mean, std=std, hidden=lstm_hidden
                )
            )

            obs = next_obs
            prev_action, prev_reward = action_val, reward


            if next_hidden is not None:
                lstm_hidden = (next_hidden[0].detach(), next_hidden[1].detach())

        # --- Calcul des Avantages (GAE) pour cet épisode ---
        advs, rets = agent.compute_gae(traj, last_value=0.0)

        # --- Ajout au GLOBAL BUFFER avec correction des Hidden States ---
        for tr, a, r in zip(traj, advs, rets):
            h_state = tr.hidden
            if h_state is None:
                # On s'assure que le premier step a un tenseur de zéros (pour le batching)
                h_zeros = torch.zeros((1, 1, 128), device=DEVICE)
                c_zeros = torch.zeros((1, 1, 128), device=DEVICE)
                h_state = (h_zeros, c_zeros)

            global_buffer.append(tr._replace(adv=a, ret=r, hidden=h_state))

        # --- MISE À JOUR DÉCLENCHÉE TOUS LES N ÉPISODES ---
        if (ep + 1) % update_every_n_episodes == 0:
            print(f"--- Mise à jour PPO (Accumulation de {update_every_n_episodes} épisodes) ---")
            agent.ppo_update(global_buffer, epochs=ppo_epochs, batch_size=batch_size)
            global_buffer = [] # On vide le buffer après l'entraînement

        agent_episode_rewards.append(ep_agent_reward)
        agent_episode_action.append(agent_action)
        global_inventory.append(episode_inventory)
        start_idx = env.idx
        print(f"[Episode {ep:03d}] Agent={ep_agent_reward:.6f} | end_idx={start_idx}")

    return agent_episode_rewards, agent_episode_action, global_inventory

"""# Test"""

def evaluate_agent(
    agent,
    env,
    n_episodes=100,
    time_horizon=100
):
    agent_rewards = []
    agent_episode_action = []      # Recupérer toutes les actions prises à chaque épisode
    global_inventory = []      # Recupérer l'évolution de l'inventaire à chaque épisode

    start_idx = 0

    for ep in range(n_episodes):

        if start_idx >= env.N - 1:
            print("Fin des données de test.")
            break

        obs = env.reset()
        env.max_steps = time_horizon

        obs = env.reset()

        episode_inventory = []
        episode_inventory.append(env.initial_inventory)
        agent_action = []   # Recupérer toutes les actions de l'épisode actuelle

        done = False

        prev_action = 0.0
        prev_reward = 0.0
        apr_buf = [[0.0, 0.0] for _ in range(env.seq_len)]

        ep_agent_reward = 0.0

        #ajout du hidden state
        lstm_hidden = None

        initial_inventory = env.initial_inventory

        while not done:

            # -------- APR --------
            apr_buf.pop(0)
            apr_buf.append([prev_action, prev_reward])
            apr = np.array(apr_buf, dtype=np.float32)

            # -------- ACTION PPO (SANS UPDATE) --------
            with torch.no_grad():
                action, logp, value, mean, std, next_hidden = agent.select_action(obs, apr, hidden=lstm_hidden)

            action_val = float(np.asarray(action).reshape(-1)[0])

            next_obs, reward, done, info = env.step([action_val])

            ep_agent_reward += reward
            agent_action.append(info["executed"])
            episode_inventory.append(env.remaining_inventory)

            obs = next_obs
            prev_action = action_val
            prev_reward = reward

            # ajout du nouveau hidden state
            if next_hidden is not None:
                lstm_hidden = (next_hidden[0].detach(), next_hidden[1].detach())

            if done:
                break

        agent_rewards.append(ep_agent_reward)
        agent_episode_action.append(agent_action)
        global_inventory.append(episode_inventory)

        start_idx = env.idx

        print(
            f"[TEST Episode {ep:03d}] "
            f"PPO={ep_agent_reward:.6f} | "
        )

    return agent_rewards, agent_episode_action, global_inventory